### ISSUE TITLE
Broken image link

### ISSUE THREAD

**Issue by hamid-m** [dantheboatman/EngineeringStatics#4]
Section 7.2 of the online version has a broken image path (see below).  I narrowed it down to [this line](https://github.com/dantheboatman/EngineeringStatics/blob/14a7fec66f5d3ae3b3b9a1216332f6afbe5d5261/source/ptx/Chapter_07.ptx#L42) in the source but didn't understand the image path convention so as to provide a pull request.

![Screenshot from 2023-02-27 10-37-26](https://user-images.githubusercontent.com/4147089/221624183-9e026311-d267-4e75-9674-c4c5df492c31.png)

**Comment by whaynes** [comment]
Thanks for finding this.  The image reference should have been 'CG-symbol', not 'cg-symbol'.
