### ISSUE TITLE
Minor Typo: Solution to Example 8.3.2

### ISSUE THREAD

**Issue by hamid-m** [dantheboatman/EngineeringStatics#6]
When solving the right hand-side, the distributed load *lower-case* *w* mistakenly becomes *upper-case* "W".  See the last two equations in the snapshot below. 
![image](https://user-images.githubusercontent.com/4147089/228606216-1324a72e-a6d3-4620-bf25-44fbf84a3fc8.png)

As before, thanks for this great resource.

**Comment by whaynes** [comment]
Fixed. 
Thank you for pointing this out.
